WITH MAIN_TABLE AS (
    SELECT 
        hired.*,
        dep."DEPARTMENT",
        job."JOB"
    FROM "DEV_EDW"."DBT__TEST_STG"."HIRED_EMPLOYEES" AS hired
    LEFT JOIN "DEV_EDW"."DBT__TEST_STG"."DEPARTMENTS" dep 
        ON hired."DEPARTMENT_ID" = dep."ID"
    LEFT JOIN "DEV_EDW"."DBT__TEST_STG"."JOBS" job 
        ON hired."JOB_ID" = job."ID"      
)

SELECT 
    "DEPARTMENT" AS department,
    "JOB" AS job,
    COUNT(CASE WHEN QUARTER("DATETIME") = 1 THEN 1 END) AS Q1,
    COUNT(CASE WHEN QUARTER("DATETIME") = 2 THEN 1 END) AS Q2,
    COUNT(CASE WHEN QUARTER("DATETIME") = 3 THEN 1 END) AS Q3,
    COUNT(CASE WHEN QUARTER("DATETIME") = 4 THEN 1 END) AS Q4
FROM 
    MAIN_TABLE
WHERE 
    YEAR("DATETIME") = 2021
    AND "JOB" IS NOT NULL
    AND "DEPARTMENT_ID" IS NOT NULL
GROUP BY 
    "DEPARTMENT", "JOB"
ORDER BY 
    "DEPARTMENT", "JOB";